# Generated by Django 5.1.1 on 2024-09-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0002_remove_message_room_remove_message_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('emoji', 'Emoji'), ('audio', 'Audio'), ('video', 'Video'), ('file', 'File'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
