# Generated by Django 5.1.2 on 2024-11-04 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0005_addeduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addeduser',
            name='added_by',
        ),
        migrations.CreateModel(
            name='UserAddHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('added_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup_login.addeduser')),
            ],
            options={
                'unique_together': {('added_user', 'added_by')},
            },
        ),
    ]
