# Generated by Django 5.1.2 on 2024-11-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0007_addeduser_added_by_delete_useraddhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addeduser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='addeduser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
